    CREATE TABLE KINGSTON
    (
        REDNI_BROJ_ZAPOSLENOG NUMBER,
        IME_ZAPOSLENOG VARCHAR2(10),
        PREZIME_ZAPOSLENOG VARCHAR2(10),
        BROJ_MASINE NUMBER,
        PLATA VARCHAR2(8),
        ISKUSTVO NUMBER,
        CONSTRAINT KINGSTON_ID_PK PRIMARY KEY (REDNI_BROJ_ZAPOSLENOG)
    )


    SELECT * FROM KINGSTON
    
    UPDATE KINGSTON SET PLATA= '900e' WHERE IME_ZAPOSLENOG='JANEZ'
    
    INSERT INTO KINGSTON VALUES (1, 'VUK', 'STOJKOVIC', 101, '835e', 2)
    INSERT INTO KINGSTON VALUES (2, 'NEMANJA', 'NIKOLIC', 132, '1010e', 3)
    INSERT INTO KINGSTON VALUES (3, 'JANEZ', 'NOVAK', 143, '900', 1)
    INSERT INTO KINGSTON VALUES (4, 'UROS', 'JOVANOVIC', 255, '1250e', 5)
    INSERT INTO KINGSTON VALUES (5, 'KATARINA', 'MARKOVIC', 346, '1100e', 3)
    INSERT INTO KINGSTON VALUES (6, 'JOVANA', 'STOJANOVIC', 441, '870e', 1)
    INSERT INTO KINGSTON VALUES (7, 'ISIDORA', 'NIKOLIC', 675, '1450e', 2)
